"""
Centraliza todas as queries SQL do projeto.

Estas queries foram extraídas DIRETAMENTE do Power Query (M) do modelo
Power BI 'Logistica_Notas_matriz', tabelas 'TFato Geral2' e 'Leadtime'.
Não são tabelas físicas no banco — são o resultado de SELECTs complexos
contra o ERP Protheus/TOTVS (tabelas SF2010, SA1010, GU3010, etc.).

IMPORTANTE: o filtro de data 'F2_EMISSAO >= 20260101' está hardcoded
no Power Query original. Mantive aqui para fidelidade, mas isso significa
que a cada virada de ano alguém precisa atualizar esse valor (tanto aqui
quanto no Power BI original). Considere parametrizar no futuro.
"""

SQL_FATO_GERAL = """
WITH VENDEDORES_PERMITIDOS AS (
    SELECT
        REPLACE(LTRIM(RTRIM(ZB5_IDVEND)), '_', '') AS COD_VENDEDOR
    FROM ZB5010
    WHERE D_E_L_E_T_ = ' '
      AND LTRIM(RTRIM(ISNULL(ZB5_COORD, ''))) <> ''
      AND REPLACE(LTRIM(RTRIM(ZB5_IDVEND)), '_', '') NOT IN (
            '000900', '000901', '0305', 'EX0018', 'EX0019', 'S00035'
      )
)
SELECT DISTINCT

    -- TRANSPORTADORA PRINCIPAL (1ª PERNA)
    GWN.GWN_CDTRP AS COD_TRANSP_PRINCIPAL,
    NULLIF(RTRIM(TP1.GU3_CDTERP), ' ') AS COD_ERP_PRINCIPAL,
    COALESCE(TP1.GU3_NMFAN, 'SEM ROMANEIO') AS TRANSP_PRINCIPAL,

    -- REDESPACHO
    COALESCE(
        NULLIF(GWU.GWU_CDTRP, ' '),
        NULLIF(SF2.F2_REDESP, ' ')
    ) AS COD_TRANSP_REDESPACHO,
    COALESCE(
        NULLIF(SF2.F2_REDESP, ' '),
        NULLIF(TP2.GU3_CDTERP, ' '),
        NULLIF(REDLKP.GU3_CDTERP, ' ')
    ) AS COD_REDESPACHO,
    COALESCE(TP2.GU3_NMFAN, RED.GU3_NMFAN) AS TRANSP_REDESPACHO,

    -- ROMANEIO
    GWN.GWN_NRROM AS ROMANEIO,

    -- NOTA
    SF2.F2_DOC AS NF,
    SF2.F2_SERIE AS SERIE,

    -- DATAS
    SF2.F2_EMISSAO AS DT_EMISSAO,
    SF2.F2_DTCARGA AS DT_SAIDA,
    GWU.GWU_DTENT AS DT_ENTREGA_REDESPACHO,
    SF2.F2_DTENTR AS DT_ENTREGA_CLIENTE,

    -- VALORES
    CAST(ITENS.VL_PRODUTOS AS DECIMAL(15,2)) AS VALOR_NF,

    -- CARGA
    SF2.F2_CARGA AS NR_CARGA,

    -- PESOS
    CAST(SF2.F2_PBRUTO AS DECIMAL(15,2)) AS PESO_BRUTO,

    -- CLIENTE
    SF2.F2_CLIENTE AS COD_CLIENTE,
    SA1.A1_LOJA AS LOJA,
    SA1.A1_NOME AS CLIENTE,
    SA1.A1_MUN AS CIDADE_CLIENTE,
    SA1.A1_EST AS UF_CLIENTE,

    -- VENDEDOR
    SF2.F2_VEND1 AS COD_VENDEDOR,
    SA3.A3_SUPER AS SUPERVISOR,

    -- TIPO FLUXO
    CASE
        WHEN GWU.GWU_CDTRP IS NOT NULL THEN 'REDESPACHO'
        ELSE 'ENTREGA DIRETA'
    END AS TIPO_FLUXO,

    -- LEAD TIME
    CAST(LT_DIRETA.Z00_LDTIME AS INT) AS LEAD_TIME_DIRETA,
    CAST(LT_REDESP.Z00_LDTIME AS INT) AS LEAD_TIME_REDESPACHO,
    CASE
        WHEN GWU.GWU_CDTRP IS NOT NULL
        THEN CAST(LT_DIRETA.Z00_LDTIME AS INT) + ISNULL(CAST(LT_REDESP.Z00_LDTIME AS INT), 0)
        ELSE CAST(LT_DIRETA.Z00_LDTIME AS INT)
    END AS LEAD_TIME_TOTAL

FROM SF2010 SF2
INNER JOIN SA1010 SA1
        ON SA1.A1_COD = SF2.F2_CLIENTE
       AND SA1.A1_LOJA = SF2.F2_LOJA
       AND SA1.D_E_L_E_T_ = ' '
INNER JOIN SA3010 SA3
        ON SA3.A3_COD = SF2.F2_VEND1
       AND SA3.D_E_L_E_T_ = ' '
INNER JOIN VENDEDORES_PERMITIDOS VP
        ON VP.COD_VENDEDOR = REPLACE(LTRIM(RTRIM(SF2.F2_VEND1)), '_', '')
INNER JOIN (
    SELECT
        D2_DOC,
        D2_SERIE,
        D2_FILIAL,
        SUM(D2_TOTAL) AS VL_PRODUTOS
    FROM SD2010
    WHERE D_E_L_E_T_ = ' '
      AND D2_FILIAL = '02'
      AND RTRIM(D2_CF) IN ('5101','5102','5105','5118','5551',
                           '6101','6102','6105','6107','6108','6109','6110','6118',
                           '6401','6403','6501','6551','7101','7127')
    GROUP BY D2_DOC, D2_SERIE, D2_FILIAL
) ITENS
        ON ITENS.D2_DOC = SF2.F2_DOC
       AND ITENS.D2_SERIE = SF2.F2_SERIE
       AND ITENS.D2_FILIAL = SF2.F2_FILIAL
LEFT JOIN GW1010 GW1
        ON GW1.GW1_NRDC = SF2.F2_DOC
       AND GW1.GW1_SERDC = SF2.F2_SERIE
       AND GW1.D_E_L_E_T_ = ' '
LEFT JOIN GWN010 GWN
        ON GWN.GWN_NRROM = GW1.GW1_NRROM
       AND GWN.D_E_L_E_T_ = ' '
LEFT JOIN GWU010 GWU
        ON GWU.GWU_NRDC = SF2.F2_DOC
       AND GWU.GWU_SERDC = SF2.F2_SERIE
       AND GWU.D_E_L_E_T_ = ' '
       AND GWU.GWU_CDTRP <> GWN.GWN_CDTRP
LEFT JOIN GU3010 TP1
        ON TP1.GU3_CDEMIT = GWN.GWN_CDTRP
       AND TP1.D_E_L_E_T_ = ' '
LEFT JOIN GU3010 TP2
        ON TP2.GU3_CDEMIT = COALESCE(NULLIF(GWU.GWU_CDTRP, ' '), NULLIF(SF2.F2_REDESP, ' '))
       AND TP2.D_E_L_E_T_ = ' '
LEFT JOIN GU3010 RED
        ON RED.GU3_CDEMIT = SF2.F2_REDESP
       AND RED.D_E_L_E_T_ = ' '
LEFT JOIN (
    SELECT
        GU3_NMFAN,
        MAX(NULLIF(RTRIM(GU3_CDTERP), ' ')) AS GU3_CDTERP
    FROM GU3010
    WHERE D_E_L_E_T_ = ' '
      AND NULLIF(RTRIM(GU3_CDTERP), ' ') IS NOT NULL
    GROUP BY GU3_NMFAN
) REDLKP
        ON REDLKP.GU3_NMFAN = TP2.GU3_NMFAN
LEFT JOIN (
    SELECT
        Z00_TRANSP, Z00_EST, Z00_CODCID,
        MAX(Z00_LDTIME) AS Z00_LDTIME
    FROM Z00010
    WHERE D_E_L_E_T_ = ' '
    GROUP BY Z00_TRANSP, Z00_EST, Z00_CODCID
) LT_DIRETA
        ON LT_DIRETA.Z00_TRANSP = NULLIF(RTRIM(TP1.GU3_CDTERP), ' ')
       AND LT_DIRETA.Z00_EST = SA1.A1_EST
       AND LT_DIRETA.Z00_CODCID = SA1.A1_COD_MUN
LEFT JOIN (
    SELECT
        Z00_TRANSP, Z00_EST, Z00_CODCID,
        MAX(Z00_LDTIME) AS Z00_LDTIME
    FROM Z00010
    WHERE D_E_L_E_T_ = ' '
    GROUP BY Z00_TRANSP, Z00_EST, Z00_CODCID
) LT_REDESP
        ON LT_REDESP.Z00_TRANSP = NULLIF(RTRIM(TP2.GU3_CDTERP), ' ')
       AND LT_REDESP.Z00_EST = SA1.A1_EST
       AND LT_REDESP.Z00_CODCID = SA1.A1_COD_MUN

WHERE SF2.F2_FILIAL = '02'
  AND SF2.D_E_L_E_T_ = ' '
  AND SA1.A1_EST <> 'EX'
  AND SF2.F2_VEND1 NOT LIKE 'EX%'
  AND SF2.F2_EMISSAO >= '20260101'
  AND SF2.F2_TRANSP <> ' '
  AND SF2.F2_TRANSP IS NOT NULL
  AND SA3.A3_SUPER <> ' '
  AND SA3.A3_SUPER <> 'S00090'
  AND SF2.F2_CLIENTE <> '015269'

ORDER BY
    SF2.F2_DOC,
    GWU.GWU_DTENT
"""


SQL_LOOKUP_NF_ENTRADA = """
SELECT DISTINCT
    SF2.F2_DOC AS NF,
    SF1.F1_DOC AS NF_ENTRADA
FROM GWN010 GWN
INNER JOIN GW1010 GW1
        ON GW1.GW1_NRROM = GWN.GWN_NRROM
       AND GW1.D_E_L_E_T_ = ' '
INNER JOIN SF2010 SF2
        ON SF2.F2_DOC = GW1.GW1_NRDC
       AND SF2.F2_SERIE = GW1.GW1_SERDC
       AND SF2.F2_FILIAL = '02'
       AND SF2.D_E_L_E_T_ = ' '
LEFT JOIN SF1010 SF1
        ON SF1.F1_NFORIG = SF2.F2_DOC
       AND SF1.F1_FILIAL = '02'
       AND SF1.D_E_L_E_T_ = ' '
       AND SF1.F1_SERIE = '5'
WHERE GWN.D_E_L_E_T_ = ' '
"""

